# Generated by Django 5.0 on 2023-12-28 15:16

import ckeditor.fields
import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_news_created_2'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description2',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=django_resized.forms.ResizedImageField(crop=None, default=1, force_format='WEBP', keep_meta=True, quality=100, scale=None, size=[1920, 1080], upload_to='news_image/', verbose_name='Фотография2'),
            preserve_default=False,
        ),
    ]
