# Generated by Django 5.0 on 2023-12-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_news_description2_news_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='description3',
            field=models.TextField(default=1, verbose_name='Описание3'),
            preserve_default=False,
        ),
    ]
